[package]
name = "bevy_prototype_animation"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy_reflect = "0.6"
bevy_asset = "0.6"
bevy_math = "0.6"
serde = "1.0"
parallel_vec = "0.2"
thiserror = "1.0"

[dev-dependencies]
rand = "0.8"

[[benches]]
name = "curves"
harness = false